[package]
name = "wigglyair"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
config = "0.13.3"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1.29.1", features = ["full", "tracing"] }
tracing = { version = "0.1.37", features = ["log"] }
tracing-bunyan-formatter = "0.3.8"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
walkdir = "2.3.3"
