#!/usr/bin/env bash

set -euo pipefail

function main() {
    if [ -z "$NAS_HOST" ]; then
        echo "NAS_HOST is not set"
        exit 1
    fi

    if [ -z "$1" ]; then
        echo "1st argument is not set"
        exit 1
    fi

    set +u
    scp -O $NAS_HOST:$1 $2
}

main "$@"
